import { createClient } from "@/lib/supabase/server"
import { NextResponse } from "next/server"
import Groq from "groq-sdk"

const GENERATION_COST = 200



export async function POST(request: Request) {
  try {
    console.log("[v0] Generate API called")

    const supabase = await createClient()

    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user) {
      console.log("[v0] No user found")
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    console.log("[v0] User authenticated:", user.id)

    const { data: userData, error: userError } = await supabase
      .from("users")
      .select("credits")
      .eq("id", user.id)
      .single()

    if (userError || !userData) {
      console.error("[v0] User fetch error:", userError)
      return NextResponse.json({ error: "Failed to fetch user data" }, { status: 500 })
    }

    console.log("[v0] User credits:", userData.credits)

    if (userData.credits < GENERATION_COST) {
      return NextResponse.json({ error: "Insufficient credits" }, { status: 402 })
    }

    let body
    try {
      body = await request.json()
    } catch (parseError) {
      console.error("[v0] JSON parse error:", parseError)
      return NextResponse.json({ error: "Invalid request body" }, { status: 400 })
    }

    const { prompt } = body

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 })
    }

    console.log("[v0] Prompt received:", prompt)

    const { data: deductResult, error: deductError } = await supabase.rpc("deduct_credits", {
      user_id: user.id,
      amount: GENERATION_COST,
    })

    if (deductError || !deductResult) {
      console.error("[v0] Credit deduction error:", deductError)
      return NextResponse.json({ error: "Failed to deduct credits" }, { status: 500 })
    }

    console.log("[v0] Credits deducted successfully")

    try {
      console.log("[v0] Initializing Groq client")
      const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY, 
});

      console.log("[v0] Calling Groq API with prompt:", prompt)

      const completion = await groq.chat.completions.create({
        messages: [
         {
  role: "system",
  content: `You are an expert Senior UI/UX Designer and Frontend Engineer. Your primary role is to convert wireframes into high-quality, production-ready, and premium web designs.

    TYPOGRAPHY & FONTS (MANDATORY):
    - You MUST include the 'Outfit' font family in the <head>:
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    - Apply it globally using Tailwind: font-family: 'Outfit', sans-serif;

    DESIGN & AESTHETICS (PREMIUM STYLE):
    - RADIUS: Use extreme corner rounding for a modern SaaS look (rounded-[2.5rem] for main containers, rounded-3xl for cards).
    - COLORS: Use vibrant primary colors (e.g., Emerald Green #10B981 or Royal Blue #2563EB). Use soft tinted backgrounds (bg-slate-50) to make white cards pop.
    - SHADOWS: Use very soft, large shadows: shadow-[0_20px_50px_rgba(0,0,0,0.04)].
    - LAYOUT: Use CSS Flexbox and Grid. Dashboard layouts must have a fixed Sidebar (left) and Top Bar.
    - SPACING: Respect wireframe heights/spaces and ensure Hero sections fit the screen perfectly.

    STRICT CODE COMPLETENESS:
    - NEVER use abbreviations, shorthand, or placeholders like 'Repeat for each member'. 
    - Every single element, section, and repetitive card MUST be fully coded individually.
    - Provide a single, complete HTML file including Tailwind CSS (via https://cdn.tailwindcss.com script) and all JavaScript.

    FUNCTIONALITY & INTERACTIVITY:
    - Use JavaScript for dropdowns, modals, and dark/light mode.
    - MOBILE MENU: Use this icon for mobile bars: https://ecommerce-build.s3.amazonaws.com/icons8-menu.svg. Ensure it is responsive and changes color based on the background.
    - ICONS: Use ONLY high-quality Inline SVG icons (Lucide/Heroicons style).

    PLACEHOLDERS:
    - Use placehold.co for placeholder images. However, for Hero sections, use high-quality Unsplash URLs.

    FINAL OUTPUT RULES:
    - Strictly output CODE ONLY. 
    - No explanations, no markdown chatter, and no partial code snippets. The client expects a ready-to-use, comprehensive solution.`
},
          {
            role: "user",
            content: prompt,
          },
        ],
        model: "llama-3.3-70b-versatile",
        temperature: 0.7,
        max_tokens: 8000,
      })

      console.log("[v0] Groq API response received")

      let generatedCode = completion.choices[0]?.message?.content || ""

      if (!generatedCode) {
        throw new Error("No code generated by Groq API")
      }

      console.log("[v0] Generated code length:", generatedCode.length)

      generatedCode = generatedCode
        .replace(/```html\n?/g, "")
        .replace(/```\n?/g, "")
        .trim()

      if (!generatedCode.includes("<!DOCTYPE html>")) {
        generatedCode = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Component</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  ${generatedCode}
</body>
</html>`
      }

      console.log("[v0] Saving project to database")

      const { error: saveError } = await supabase.from("projects").insert({
        user_id: user.id,
        title: prompt.slice(0, 100),
        prompt: prompt,
        generated_code: generatedCode,
        framework: "html",
        language: "javascript",
      })

      if (saveError) {
        console.error("[v0] Failed to auto-save:", saveError)
      } else {
        console.log("[v0] Project saved successfully")
      }

      return NextResponse.json({
        code: generatedCode,
        creditsRemaining: userData.credits - GENERATION_COST,
      })
    } catch (groqError: any) {
      console.error("[v0] Groq API Error:", groqError)
      console.error("[v0] Error message:", groqError?.message)
      console.error("[v0] Error stack:", groqError?.stack)

      try {
        console.log("[v0] Attempting to refund credits")
        const { error: refundError } = await supabase
          .from("users")
          .update({ credits: userData.credits })
          .eq("id", user.id)

        if (refundError) {
          console.error("[v0] Failed to refund credits:", refundError)
        } else {
          console.log("[v0] Credits refunded successfully")
        }
      } catch (refundError) {
        console.error("[v0] Exception during refund:", refundError)
      }

      return NextResponse.json(
        {
          error: groqError?.message || "Failed to generate code. Your credits have been refunded.",
        },
        { status: 500 },
      )
    }
  } catch (error: any) {
    console.error("[v0] Unexpected error in generate route:", error)
    console.error("[v0] Error message:", error?.message)
    console.error("[v0] Error stack:", error?.stack)
    return NextResponse.json({ error: "An unexpected error occurred" }, { status: 500 })
  }
}
